- year: "2025"
  role: "Co-Organizer"
  event: "Responsible Speech & Audio Generative AI"
  link: "https://codecfake.github.io/RespSA-GenAI/"
  context: "Special Session at IEEE ASRU 2025"
  selected: true

- year: "2024"
  role: "Technical Committee"
  event: "Codec-SUPERB Challenge"
  link: "https://codecsuperb.github.io/"
  context: "Special Session at IEEE SLT 2024"
  selected: true

- year: "2023â€“Now"
  role: "Reviewer"
  all_event: "ICML, AAAI, ACL, EMNLP, ICASSP, INTERSPEECH, ASRU, COLING, MLSP, IJPRAI"
  event: "ICML, AAAI, ACL, EMNLP, ICASSP, ICME, INTERSPEECH, ASRU, COLING, IJPRAI"
  selected: true
